params = {
    "glue_dataset_name": "cola",
    "model_name": "roberta-base",
    "use_hypernet": True,

    "lora_r": 8,
    "lora_alpha": 16,

    "hypernet_hidden_dim": 512,
    "hypernet_embeddings_dim": 128,
    "layers_to_use_hypernet": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    "hypernet_use_on_value_matrix": True,
    "hypernet_with_embedding_input_only": True,
    "hypernet_large_model": False,
    "hypernet_use_fixed_A": True,

    "output_dir": f"./outputs/hypernet",
    "eval_strategy": "epoch",
    "eval_steps": 5,
    "save_strategy": "steps",
    "save_steps": 1000000000,
    "logging_strategy": "epoch",
    "logging_steps": 50,
    "learning_rate": 4e-4,
    "weight_decay": 0.1,
    "per_device_train_batch_size": 16,
    "per_device_eval_batch_size": 32,
    "gradient_accumulation_steps": 2,
    "num_train_epochs": 20,
    "metric_for_best_model": "matthews_correlation",
    "warmup_ratio": 0.06,
    "lr_scheduler_type": "linear",
    "optim": "adamw_torch",
    "disable_tqdm": True,

    "results_dir": "./results/ablation_2",

    "num_runs": 1,
    "seed": 11,
}
